# Generated by Django 5.1.6 on 2025-03-01 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('abstract', models.TextField(verbose_name='Resumo')),
                ('content', models.TextField(verbose_name='Conteúdo Principal')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação')),
                ('section', models.CharField(max_length=100, verbose_name='Seção')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_root', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
